# gfci_graphviz:  make graphviz dot file from results generated by rcausal method

library(Rgraphviz)
gfci_graphviz <- function(gfci, loc="./jci/results/sachsGraph.dot", cmp=FALSE) {
  # file.create(loc)
  # fileConn<-file(loc)
  edges <- gfci$edges
  nodes <- gfci$nodes
  dotfile <- c("digraph ofzo {", "node [color=lightblue2, style=filled];")
  
  if (cmp == TRUE) {
    dotfile <- c(dotfile, "edge [color=blue];")
    aci <- c("Mek -> Raf","Mek -> Erk","Mek -> Akt","Mek -> JNK","PIP2 -> PLCg","Akt -> JNK","PKA -> Raf","PKA -> Mek","PKA -> Akt","PKA -> p38","PKA -> JNK","PKC -> Raf","PKC -> Mek","PKC -> PLCg","PKC -> PIP2","PKC -> PIP3","PKC -> Erk","PKC -> Akt","PKC -> JNK","PKC -> p38")
  }
  
  for (node in nodes) {
    dotfile <- c(dotfile, paste("\"", node, "\";", sep=""))
  }

  
  for (edge in edges) {
    edgeNodes <- strsplit(edge, " ")

    connection <- edgeNodes[[1]][2]
    edgeNodes <- edgeNodes[[1]][-2]
    
    if (cmp == TRUE) {
      extra <- ""
      if (edge %in% aci) {
        extra <- "[color=black]"
      }
      dotfile <- c(dotfile, paste("\"", edgeNodes[1], "\" -> \"", edgeNodes[2], "\" ",extra, ";",sep=""))
      
    } else {
      if (connection == "o->") {
        dotfile <- c(dotfile, paste("\"", edgeNodes[1], "\" -> \"", edgeNodes[2], "\" [dir=both arrowtail=dot];",sep=""))
      } else if (connection == "o-o") {
        dotfile <- c(dotfile, paste("\"", edgeNodes[1], "\" -> \"", edgeNodes[2], "\" [dir=both arrowtail=dot arrowhead=dot]",  sep=""))
      } else {
        dotfile <- c(dotfile, paste("\"", edgeNodes[1], "\" -> \"", edgeNodes[2], "\";",sep=""))
      }
    }
  }
  
  dotfile <- c(dotfile, "}")
  write(x=dotfile,file=loc)
  # writeLines(dotfile, fileConn)
  # close(fileConn)
}